# Generated by Django 2.2.7 on 2020-03-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200310_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Coral',
        ),
    ]
