# Generated by Django 2.2.7 on 2020-03-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200311_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoralType',
            new_name='Coral_type',
        ),
        migrations.AlterField(
            model_name='coral',
            name='flow',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=12),
        ),
        migrations.AlterField(
            model_name='coral',
            name='light',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=12),
        ),
    ]
