# Generated by Django 2.2.7 on 2020-03-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200312_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previous_order',
            name='coral',
        ),
        migrations.AddField(
            model_name='previous_order',
            name='coral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Coral'),
        ),
    ]
