# Generated by Django 2.2.7 on 2020-03-12 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200312_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_order',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='previous_order',
            name='coral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Coral'),
        ),
    ]
