# Generated by Django 2.2.7 on 2020-03-12 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20200312_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Checkout',
        ),
    ]
