# Generated by Django 2.2.7 on 2020-03-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200312_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coral_type',
            new_name='CoralType',
        ),
        migrations.RenameField(
            model_name='coral',
            old_name='coralType',
            new_name='coral_type',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='coral',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('coral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Coral')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
