# Generated by Django 2.2.7 on 2020-03-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200315_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
