# Generated by Django 2.2.7 on 2020-03-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200315_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='coral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Coral'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='coral',
        ),
        migrations.AddField(
            model_name='order',
            name='coral',
            field=models.ManyToManyField(through='api.Checkout', to='api.Coral'),
        ),
    ]
