# Generated by Django 2.2.7 on 2020-03-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='order',
            new_name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Checkout'),
        ),
    ]
