# Generated by Django 2.2.7 on 2020-03-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_checkout_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
