# Generated by Django 2.2.7 on 2020-03-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200318_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_checkout',
            name='pyment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Knet', 'Knet'), ('Visa', 'Visa')], default='Knet', max_length=12),
        ),
    ]
