# Generated by Django 2.2.7 on 2020-03-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_order_coral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='coral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Coral'),
        ),
    ]
