# Generated by Django 2.2.7 on 2020-03-23 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_order_checkout_pyment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Order_Checkout',
            new_name='OrderCheckout',
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='api.OrderCheckout'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='coral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Coral'),
        ),
    ]
